// Generated by CoffeeScript 1.9.3
(function() {
  var error;

  error = function(text) {
    return '\x1b[31mError: \x1b[0m\x1b[1m\x1b[31m' + text + '\x1b[0m';
  };

  module.exports = error;

}).call(this);
