// Generated by CoffeeScript 1.9.3
(function() {
  var code, exec, filename, fs, l, lex, new_time, p, parse, print_lex, print_parsed, t, time;

  lex = require('./lex.js');

  parse = require('./parse2.js');

  exec = require('./exec.js');

  print_lex = require('./print-lex.js');

  print_parsed = require('./print-parsed.js');

  fs = require('fs');

  filename = process.argv[2];

  time = new Date();

  code = fs.readFileSync(filename).toString();

  l = lex(code);

  p = parse(l);

  exec(p);

  new_time = new Date();

  t = time.getTime() - new_time.getTime();

  console.log(Math.abs(t) + 'ms' + ' | ' + Math.abs(t / 1000) + 's');

}).call(this);
